### ISSUE TITLE
Readthedocs docs

### ISSUE THREAD

**Issue by philipstarkey** [labscript-suite/labscript-suite#19]
**Original report ([archived issue](https://labscript-suite.github.io/labscript-suite-bitbucket-archive/#!/labscript_suite/installer/issues/19)) by Chris Billington (Bitbucket: [cbillington](https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/), GitHub: [chrisjbillington](https://github.com/chrisjbillington)).**

----------------------------------------
The installer needs sphinx documentation hosted on readthedocs or similar, including a getting started guide.

**Comment by rpanderson** [comment]
Resolved by #37, #42, #43, #47, #48.
