### ISSUE TITLE
Rename this repository to something like 'labscript_suite' and have it contain central docs etc

### ISSUE THREAD

**Issue by philipstarkey** [labscript-suite/labscript-suite#24]
**Original report ([archived issue](https://labscript-suite.github.io/labscript-suite-bitbucket-archive/#!/labscript_suite/installer/issues/24)) by Chris Billington (Bitbucket: [cbillington](https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/), GitHub: [chrisjbillington](https://github.com/chrisjbillington)).**

----------------------------------------
Open source projects commonly have a single repository that acts as a landing page with an informative README and all the rest for the project as a whole. We don't have one of these.

Make the installer repo take on this role, by renaming it to 'labscript_suite' or similar, and have it contain any 'getting started' or otherwise common documentation. Then this repository can be the one linked to when we want to link to 'the development repository'. The README will explain that there are subprojects under different version control repos.

Having a landing page like this is important for giving people encountering the project for the first time a good sense of what a project is about. 'getting started' sphinx docs can be configured to render both to a README file and to readthedocs.io, such that someone being linked here can get a good introduction from the README alone, with a 'click here for more' linking to readthedocs. All these things are also great for search engine visibility.

**Comment by rpanderson** [comment]
Resolved by #37.
