### ISSUE TITLE
Extremely basic end-to-end test to verify currently tagged versions not broken

### ISSUE THREAD

**Issue by philipstarkey** [labscript-suite/labscript-suite#27]
**Original report ([archived issue](https://labscript-suite.github.io/labscript-suite-bitbucket-archive/#!/labscript_suite/installer/issues/27)) by Chris Billington (Bitbucket: [cbillington](https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/), GitHub: [chrisjbillington](https://github.com/chrisjbillington)).**

----------------------------------------
We have had a few regressions due to testing always happening with the latest development versions and not the releases. In principle we are supposed to recognise when we have introduced dependency between components or modified one in a backward compatible way so that the version checks detect a problem, but we have missed this on a number of occasions.

We need a basic end-to-end test that installs the labscript suite in a fresh environment using the installer and runs a dummy experiment through all the programs to verify there is no major incompatibility that say, prevents a program from starting.

**Comment by rpanderson** [comment]
Duplicates #23. Meaning/use of tags changed since migrating to GitHub.
