### ISSUE TITLE
Provide example command for pip or conda install.

### ISSUE THREAD

**Issue by philipstarkey** [labscript-suite/labscript-suite#3]
**Original report ([archived issue](https://labscript-suite.github.io/labscript-suite-bitbucket-archive/#!/labscript_suite/installer/issues/3)) by Chris Billington (Bitbucket: [cbillington](https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/), GitHub: [chrisjbillington](https://github.com/chrisjbillington)).**

----------------------------------------
Provide an example command to install missing dependencies via conda or pip. Provide instructions to the user that if they are in a conda environment, that `pip` may refer to the system wide pip, and they should be sure to `conda install pip` before `pip install`ing anything

**Comment by rpanderson** [comment]
Closing this as v3.0 releases are now available on [PyPI](https://pypi.org/user/labscript-suite/) and [Anaconda Cloud](https://anaconda.org/labscript-suite), and installation documentation is available for all permutations [here](https://docs.labscriptsuite.org/en/stable/installation).
