### ISSUE TITLE
Change sudo behaviour on unix

### ISSUE THREAD

**Issue by philipstarkey** [labscript-suite/labscript-suite#30]
**Original report ([archived issue](https://labscript-suite.github.io/labscript-suite-bitbucket-archive/#!/labscript_suite/installer/issues/30)) by Chris Billington (Bitbucket: [cbillington](https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/), GitHub: [chrisjbillington](https://github.com/chrisjbillington)).**

----------------------------------------
So far, if you want to install the labscript suite with system Python on unix, you need to run the installer with `sudo`, so that it has permission to write the `.pth` file to the site-packages dir.

However, I just ran the installer with sudo, and it had the side effect of picking `/root/labscript_suite` as the default install directory. Other settings based on the home directory are presumably wrong too.

I'm not sure if this is distro-specific (don't remember it being a problem on Ubuntu), or whether sudo itself has changed, but in either case we should probably not be inspecting the `$HOME `environment variable while running under sudo, in case it is wrong.

The fix, which is probably a good idea anyway, would be to create the .pth file as a temporary file, then run a 'sudo mv' command that will prompt for the user's password just for that command. Then the rest of the script won't be running as root, which is safer. The user also won't accidentally run the script without root only to find they have to run it again after getting a permissions error.

The code should probably try to run `mv` without sudo first, running it again with sudo only if it gets a permission error.

**Comment by rpanderson** [comment]
Closing as the installer is no longer used now that the labscript suite is distributed as Python packages on [PyPI](https://pypi.org/user/labscript-suite) and [Anaconda Cloud](https://anaconda.org/labscript-suite). See the [installation guide](https://docs.labscriptsuite.org/en/latest/installation) for details.
