### ISSUE TITLE
Tasks required before moving to standard Python packages

### ISSUE THREAD

**Issue by philipstarkey** [labscript-suite/labscript-suite#31]
**Original report ([archived issue](https://labscript-suite.github.io/labscript-suite-bitbucket-archive/#!/labscript_suite/installer/issues/31)) by Chris Billington (Bitbucket: [cbillington](https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/), GitHub: [chrisjbillington](https://github.com/chrisjbillington)).**

----------------------------------------
This is a list of the things we will need to do before we can move to having standard Python packages for labscript suite components. We can check things off as they are done

* ~~Implement a 'user_devices' folder so that users can add devices outside of labscript_devices whilst hacking on them~~ (done, [labscript_utils PR #81](https://bitbucket-archive.labscriptsuite.org/#!/labscript_suite/labscript_devices/pull-requests/81))
* ~~Create log files within a 'logs' directory under the labscript suite install directory~~ (done, [labscript_utils #PR 95](https://bitbucket-archive.labscriptsuite.org/#!/labscript_suite/labscript_utils/pull-requests/95))
* Finish the changes to BLACS that would allow it to import unit calibration classes from anywhere, and not just from within labscript_utils.
* Convert each project into the standard repo layout with a setup.py
* ~~Brainstorm what the installer should be and do. Should there even be an installer? Perhaps the installer can simply be the setup.py of a 'labscript_suite' package that pulls in the latest versions of all the other packages and sets up the directories. Can we install the labscript suite components into the labscript suite install directory? Should we? We will still need to do path manipulation with a .pth file, since userlib and its subdirectories will still exist and need to be importable~~. Brainstorming done, see comment below. Yet to do: implement this
* ~~Modify `labscript_utils.winshell` functions that refer to packages' `__main__.py` files and icon files to find them according to the import path of the package instead of assuming they are within the labscript suite install directory.~~(done, labscript_utils [PR #96](https://bitbucket-archive.labscriptsuite.org/#!/labscript_suite/labscript_utils/pull-requests/96))
* Modify BLACS and possibly others to look up their file resources based on the `__file__` attribute of their modules rather than assuming a fixed location within the labscript suite install directory (we actually switched BLACS to *not* use `__file__` at one point because it was error-prone in the presence of `os.chdir()` calls. But in Python 3 this is less of an issue since `__file__` is absolute unless the main script was run with a relative path. Even then, a single `__file__` lookup in `__init__.py` should be unproblematic).

Phil mentioned implementing our planned backward-incompatible changes to communication between programs when we make this change. I don't think that is super important, since although the changes are backward incompatible, they are detectable at run time as being incompatible and users will be prompted to upgrade. So I don't think we need to roll this out at the same time necessarily.

**Comment by rpanderson** [comment]
Resolved by #37 and other recent changes. As of v3.0 releases are now available on [PyPI](https://pypi.org/user/labscript-suite/) and [Anaconda Cloud](https://anaconda.org/labscript-suite), and installation documentation is available for all permutations [here](https://docs.labscriptsuite.org/en/stable/installation).
