### ISSUE TITLE
Tasks relating to leaving BitBucket hosting

### ISSUE THREAD

**Issue by philipstarkey** [labscript-suite/labscript-suite#32]
**Original report ([archived issue](https://labscript-suite.github.io/labscript-suite-bitbucket-archive/#!/labscript_suite/installer/issues/32)) by Philip Starkey (Bitbucket: [philipstarkey](https://bitbucket.org/%7B0147401a-13ed-4e39-a0d0-63108c18738b%7D/), GitHub: [philipstarkey](https://github.com/philipstarkey)).**

----------------------------------------
**Please note: General discussion on the migration should be kept on the mailing list \(see** [**here**](https://groups.google.com/forum/#!topic/labscriptsuite/-lpbHNN1h5I)**\). This issue is for keeping track of the tasks and our progress.**

Regardless of the final decision we make on a destination \(the favourite currently being GitHub\), there are some things we need to do before we migrate repositories away from BitBucket \(forced on us due to the removal of mercurial support\). This issue should be used to keep track of them \(feel free to add more as we determine what they are\).

These are:

* Triage/merge all pull requests
* Look at the public forks of each component and import them into the new hosting \(this will help preserve the history of pull requests, particularly those that were **declined** or that we decline on BitBucket now because solving the remaining issue is too time consuming at the moment, but we might want to restart the pull request later\).
* Implement issue #31
* import repositories to new host
* Export/backup whatever we can from Bitbucket \(issues, pull requests, etc\) before it is deleted on 31st May 2020
* Consider improving the Bitbucket → GitHub issue importer

    * I think we should be able to provide a list of access tokens for many users, so that comments are correctly attributed to most authors.
    * Consider finding/replacing changeset links in issue comments
    * Consider matching and updating links to issues in other repositories
    * Handle mismatch to pull request numbers
    * We could in theory consider doing something similar for Pull Requests…make fake pull requests \(and decline them\) so that we get the pull request history into GitHub \(requires us to figure out how to scrape it from Bitbucket though.
    
* Import issues to GitHub
* Put up Git placeholder repos in all existing Bitbucket repository locations we control, pointing people to the new location \(this is so people reading out theses/papers can ‘easily’ find the new code location\)

‌

Things to figure out on GitHub \(assuming we move there\):

* How GitHub organisations work \(so that all labscript suite repositories are contained together\)

    * On BitBucket we have a labscript\_suite team with subprojects under that for the labscript suite and for hardware devices. The former should map to organisations I think, but I haven’t checked how to group repositories within an organisation yet.
    
* Do some tests on the fork/pull request workflow so we get the hang of it and can update instructions accordingly
* The use of GitHub pages \(possibly for hosting a static HTML repository of the old Bitbucket pull requests\)
* Integration with readthedocs

**Comment by rpanderson** [comment]
labscript suite repositories were migrated to GitHub and the above (and much more!) were undertaken during April–June 2020. See [here](http://docs.labscriptsuite.org/en/stable/changes) for details.
