### ISSUE TITLE
Rename this repo "labscript-suite" and have it become the metapackage

### ISSUE THREAD

**Issue by chrisjbillington** [labscript-suite/labscript-suite#35]
We should have a metapackage such that you can `pip install labscript-suite`. This metapackage should depend on the other packages, and basically otherwise be a dummy package. If we are tempted to add suite-wide functionality, most of that should probably be in `labscript_utils` rather than a metapackage.

The metapackage github repo could also be the place to discuss issues not obviously applying to a specific repository.

I'll file a pull request implementing this, and if there are no objections I'll merge it and rename the repository.

**Comment by chrisjbillington** [comment]
Rename done, metapackage not done.

**Comment by rpanderson** [comment]
Metapackage done in #37.
