### ISSUE TITLE
Pre-pip installation

### ISSUE THREAD

**Issue by dihm** [labscript-suite/labscript-suite#36]
So I'm trying to set up a labscript installation and I would like to avoid using the older hg-based installer. It there any general guidance for installing right now from github repos without pip? 

Is there need for a beta-tester for pip packages? I wouldn't mind helping there if I can since I'm working on a clean installation anyway. 

If all else fails, I believe a manual install only entails cloning repos, setting up the path file, then running the shortcut fixer from labscript_utils. Am I missing anything?

**Comment by chrisjbillington** [comment]
Hey David,

Thanks for your ever-present enthusiasm for testing!

Shouldn't be too long before we push to pip, but in the meantime, a standard development setup looks like (we have just figured this out ourselves and should document it as well for contributors) is the following. This will clone all the repositories to your local directory and install them in editable mode.

(don't know whether hashes count as comments in windows so maybe don't copy-paste the whole lot)

```bash
# Set up a virtual environment and some dependencies that are not automatically pulled in
python -m venv .venv
source .venv/bin/activate
python -m pip install --upgrade pip setuptools wheel PyQt5

pip install \
  --src . -e git+https://github.com/labscript-suite/blacs#egg=blacs \
  --src . -e git+https://github.com/labscript-suite/labscript#egg=labscript \
  --src . -e git+https://github.com/labscript-suite/labscript-devices#egg=labscript-devices \
  --src . -e git+https://github.com/labscript-suite/labscript-utils#egg=labscript-utils \
  --src . -e git+https://github.com/labscript-suite/runmanager#egg=runmanager \
  --src . -e git+https://github.com/labscript-suite/runviewer#egg=runviewer
  --src . -e git+https://github.com/chrisjbillington/desktop-app#egg=desktop-app
# creates labscript-suite in your home directory, this is the new location of user data:
labscript-profile-create 
# Start menu shortcuts, optional. If you want to not clash with an existing install, name your virtual environment something other than `.venv` and the start menu shortcuts should include it in the name
desktop-app install blacs
desktop-app install lyse
desktop-app install runmanager
desktop-app install runviewer
```

You can run the apps from the terminal in the venv as just `blacs`, `lyse`, etc, or `blacs-gui`, `lyse-gui` etc to run them detached from the console. You won't have proper taskbar icons unless you run the desktop-app commands above (though I'm working on it :p). You also might not have taskbar icons distinct from the Python.exe icon at all if using Python from the Microsoft Store, though I'm working on that too.

No conda packages yet, though if you were to install the dependencies (I don't have a centralised list, they're in the individual setup.py scripts) in conda, the above pip installs would work fine in a conda env as well.

Just gotta merge a couple of pull requests before those `desktop-app` lines will work, gimme a few minutes :)

**Comment by chrisjbillington** [comment]
> If all else fails, I believe a manual install only entails cloning repos, setting up the path file, then running the shortcut fixer from labscript_utils. Am I missing anything?

Whilst this route would still work somewhat, the .pth file would need to contain the path to every clone separately, since the modules are now one layer deeper within each repo due to the restructuring to a standard Python package layout.

The shortcut fixer will break for the same reason, it will get the paths to the apps wrong since they moved. Rather than fix it, we're moving the shortcut-creation and taskbar integration business out into a [separate project](https://github.com/chrisjbillington/desktop-app)

**Comment by dihm** [comment]
Perfect! I figured I was going to miss something, so I'm glad I asked first. 

The install appears to have worked. Two minor comments: you forgot the lyse install line in the above code block, and the line continuation character for the windows CMD is `^` not `/`.

As for conda deps, I keep dreaming that one day pip and conda will play nicely. Too bad that day will probably never come. I have to say it is a little annoying that conda has `importlib_metadata` and pip has `importlib-metadata`. 

Anyway, runviewer, runmanager, and lyse open so I'm sure blacs will too once I get the connection table sorted.

**Comment by chrisjbillington** [comment]
Thanks, edited my comment to fix to errors for posterity.

Yeah, pretty annoying about conda and pip lack of interoperabilty. I'm trying to automate generation of conda recipes based almost solely on setuptools info, though it needs the few remaining package names that differ.
 
FWIW pip should treat hyphens and underscores interchangably! You should be able to `pip install importlib_metadata`

**Comment by rpanderson** [comment]
Hi David,

Beta releases of the entire suite are now on [PyPI](https://pypi.org/user/labscript-suite/), including the labscript-suite metapacakge that this repository has become (see README.md). This means you the entire installation process is essentially:
```
$ pip install labscript-suite[pyqt5]
$ labscript-create-profile
$ desktop-app install blacs lyse runmanager runviewer
```
There's a lot more detail in the documentation we've been working on, which can be found at [docs.labscriptsuite.org](https://docs.labscriptsuite.org). We'd be very grateful for any feedback you have on the [installation](https://docs.labscriptsuite.org/en/latest/installation/) and [contributing](https://docs.labscriptsuite.org/en/latest/contributing/) guides. These are a work in progress and currently don't include instructions for performing a regular or development installation using `conda`.

**Comment by rpanderson** [comment]
> No conda packages yet, though if you were to install the dependencies (I don't have a centralised list, they're in the individual setup.py scripts) in conda, the above pip installs would work fine in a conda env as well.

Conda packages are coming soon. In the meantime a centralised list as of the 3.0beta releases is here:
https://gist.github.com/rpanderson/175f70fc3261fec909cd880ed4644075

**Comment by dihm** [comment]
An actual documentation website--Hallelujah! It looks awesome. Can't wait for it to flesh out even more. I'm also liking the detailed instructions for using the development install day-to-day. That's going to save me a lot of headaches down the road (shakes-fist-at-git).

Now that pip is out, I suppose I can close this issue. I do have one final question. Looking at release numbers on pip, many of the packages are showing version 1.0 when the actual module release numbers are quite different. Is that intentional or are things still in flux? Also, do I see hints of labscript v3 finally?

**Comment by chrisjbillington** [comment]
Thanks for your kind words!

The 1.0 'releases' are whatever one of us uploaded in 2014 and are not the recent work. If you click on the 'releases' tab in PyPI you'll see beta releases with higher version numbers that we've been uploading more recently and that you can download if you add the `--pre` option to pip. But we'll have non-beta releases our pretty soon, things are coming together finally.

unfortunately "labscript 3" does not imply the existence of the features I wanted to see in the next-generation version of labscript, it's simply the case that we've broken backward compatibility in a pretty major way now, with official dropping of support for anything less than Python 3.6, and so that implies a major version bump. The hypothetical but glorious future of the labscript compiler will now be referred to as 'labscript 4' :p.

**Comment by chrisjbillington** [comment]
Ah also, conda packages are now here. Next thing on my list is to add the conda option to the documentation, but the following in a fresh-ish conda env should do the trick:
```bash
$ conda install -c labscript-suite/label/test labscript-suite pyqt
$ labscript-profile-create
$ desktop-app install lyse runmanager blacs runviewer
```

**Comment by rpanderson** [comment]
Closing this as v3.0 releases are now available on [PyPI](https://pypi.org/user/labscript-suite/) and [Anaconda Cloud](https://anaconda.org/labscript-suite), and installation documentation is available for all permutations [here](https://docs.labscriptsuite.org/en/stable/installation).

**Comment by rpanderson** [comment]
Closing this as v3.0 releases are now available on [PyPI](https://pypi.org/user/labscript-suite/) and [Anaconda Cloud](https://anaconda.org/labscript-suite), and installation documentation is available for all permutations [here](https://docs.labscriptsuite.org/en/stable/installation).
