### ISSUE TITLE
m2r breaks docs build when used with mistune>=2.0.0

### ISSUE THREAD

**Issue by dihm** [labscript-suite/labscript-suite#65]
Significant updates to mistune have broken m2r, and it appears m2r is no longer maintained. There is a follow on effort called m2r2, but all it does is pin mistune==0.8.4 and break the sphinx linkages due to the minor name changes.

Need to go through all the repos and update setup.cfg to pin mistune<2.0.0 to fix this for the time being.

**Comment by dihm** [comment]
Updated the whole suite. Of course a couple components now fail to build docs for an entirely new reason.

`labscript`, `lyse`, and `runmanager` fail with many, many nested levels of the error:

```shell
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/labscript/envs/latest/lib/python3.7/site-packages/labscript_utils/ls_zprocess.py", line 322, in connect_to_zlock_server
    client.ping(timeout=0.05)
  File "/home/docs/checkouts/readthedocs.org/user_builds/labscript/envs/latest/lib/python3.7/site-packages/zprocess/zlock/__init__.py", line 105, in ping
    self._new_socket(timeout)
  File "/home/docs/checkouts/readthedocs.org/user_builds/labscript/envs/latest/lib/python3.7/site-packages/zprocess/zlock/__init__.py", line 85, in _new_socket
    'tcp://%s:%s' % (self.host, str(self.port)), timeout
  File "/home/docs/checkouts/readthedocs.org/user_builds/labscript/envs/latest/lib/python3.7/site-packages/zprocess/security.py", line 251, in connect
    raise TimeoutError('Could not connect to server: timed out')
zprocess.utils.TimeoutError: Could not connect to server: timed out
```

Appears better mocking of `ls_zprocess` is needed, though not entirely sure why the change nor why only these components fail. Will have to investigate later.

**Comment by dihm** [comment]
Did a little quick testing in labscript-suite/labscript#87.

I have determined that changes in zprocess and labscript-utils versions are not the culprit. Looking closer at the logs, it appears the issue lies in the version import in the docs `conf.py` file. These three modules import significant portions of their code base when importing the module (via `__init__.py`), including calls to `labscript_utils.h5lock`, which may be the ultimate culprit.

As for why it's different now, I'm still not sure. Best I can tell, RTD has made a major release that maybe changed some underlying functionality that we were implicitly relying on. In any case, because the failure happens in `conf.py` and not during the actual build, standard autodoc mocking doesn't work.

**Comment by chrisjbillington** [comment]
Any module with intentional import side effects like h5lock could be modified to just be like "If on readthedocs, don't". There's an environment variable they can check. Would that be easier than mocking?

Any any module with non-intentional import side effects - we should take a look and consider removing the side effects.

**Comment by dihm** [comment]
OK, so I managed to get something working that is fairly painless. Basically I'm just side-stepping the import side effects that lead to attempts to contact `zlock` or `zlog` servers (which aren't running on the docker build instance of RTD).

First, I use `importlib_metadata` to get the version in `conf.py`. This prevents sphinx from trying to actually import the module in the initialization stage. Next, I use sphinx's built-in `autodoc_mock_imports` capability to mock all `labscript_utils` imports for any autodoc/autosummary imports during the documentation build phase. These two combine have fixed the build (for `labscript` at least, I've been burned before assuming things will be common across the suite).


>Any any module with non-intentional import side effects - we should take a look and consider removing the side effects.

I certainly agree with this, though I'm not entirely sure how to tell the difference between intentional and non-intentional.

**Comment by chrisjbillington** [comment]
> I certainly agree with this, though I'm not entirely sure how to tell the difference between intentional and non-intentional.

h5_lock monkey-patching h5py and connecting to a zlock server on import is intentional - we want that to work whenever merely imported. Pretty much anything else isn't as far as I'm aware, and ought to be able to be moved into `__init__` methods or `if __name__ == '__main__'` blocks if it's causing trouble.

**Comment by dihm** [comment]
Ah, OK. I'm reasonably confident the issue lies in h5_lock so I'll just go ahead and implement the work-around where it's needed. For better or worse, the mocking only works at the top module level, so it will hide other issues in labscript_utils, but that will just have to do I guess.

**Comment by dihm** [comment]
OK, so all the docs builds are working again. Finally. Hopefully the next round of bit-rot takes a little longer to come up.
