### ISSUE TITLE
setuptools > 64 breaks editable installs

### ISSUE THREAD

**Issue by dihm** [labscript-suite/labscript-suite#74]
Looks like pip and setuptools finally implemented P[EP 660](https://peps.python.org/pep-0660/) and it breaks how our entry points are handled (see [here](https://groups.google.com/g/labscriptsuite/c/ZqgutA3s-_0)).

@chrisjbillington If you have any thoughts on how to quickly fix this, I'm all ears. If not, I'll take a stab at fixing it this week. If I can't figure it out quickly I'll just pin down setuptools and push a hotfix for the near term.

**Comment by chrisjbillington** [comment]
The fix will need in to be in `desktop-app`, which uses some of the import machinery to find the package directory:

https://github.com/chrisjbillington/desktop-app/blob/master/desktop_app/environment.py#L94

A more literal use of the import machinery would probably work (given the module should be importable!), but we wanted to exclude the common bug of returning the current working directory, for the case when you happen to be working in the source directory but it's *not* an editable install. In an editable install the same path ought to be in sys.path still, but as an absolute filepath which the code won't exclude. So we're not just using the basic "importlib.util.find_spec" which ought to work to find any importable module without importing it.

Shouldn't be too hard to fix if I can reproduce it. Should have some time this week. Or feel free to take a look at `get_package_directory()` and debug why `PathFinder.find_spec()` can't find the module but presumably `importlib.util.find_spec()` does.

**Comment by chrisjbillington** [comment]
Hopefully fixed here in `desktop-app`

https://github.com/chrisjbillington/desktop-app/commit/3701c2b28b6fc89e5dfa76888f1ab5407daa1c76

The new way of doing editable installs causes a problem both for `desktop-app install` and for the launcher, this ought to fix both.

The new way of doing editable installs seems pretty good, it's just a pain having to keep up with changes like this. If we can think of ways to be less magical and thus not be so fragile to changes like that that would be better, but I suspect a lot of it is unavoidable.

If this seems to fix the problem I'll tag a `desktop-app` release and it should propagate to the conda channel.

**Comment by chrisjbillington** [comment]
This should be fixed and released in `desktop-app`
