### ISSUE TITLE
Update installation instructions regarding forking

### ISSUE THREAD

**Issue by philipstarkey** [labscript-suite/labscript-suite#81]
It looks like GitHub has added a feature in the last year or so that allows you to only fork the `master` branch. If you do this with labscript, you don't get any tags. Which then breaks our versioning detection system and possibly leads to preventing installation in at least some cases. See the mailing discussion: https://groups.google.com/u/1/g/labscriptsuite/c/pE4SO1NuXPw

We should explicitly tell people to uncheck the box on the fork page. Possibly include a screenshot for that too.

**Comment by dihm** [comment]
Wow, that is really annoying. Why would you want to delete all tags on the default branch of a project you fork?

And talk about subtle. I can barely even find mention of it, and what [I do find](https://github.blog/changelog/2022-07-27-you-can-now-fork-a-repo-and-copy-only-the-default-branch/) is ambiguous: "With this new feature, only the default branch is copied; no other branches or tags." Feel like it's pretty easy to assume that only means tags on the other branches.

Whatever, I'll update the installation docs.
